name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # 👇 Use Docker container for all steps
    container:
      image: python:3.10-slim

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Install dependencies (Python is already available in the container)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt
          pip install pytest  # Optional: Ensure pytest is installed

      # Step 3: Run tests
      - name: Run tests
        run: pytest

